[features]
seeds = false
[programs.localnet]
spin = "GSZNsGYUVXeisnKaKQ2mN6YQZScmWRG2wFnybX7F8Buj"

[programs.devnet]
spin = "GSZNsGYUVXeisnKaKQ2mN6YQZScmWRG2wFnybX7F8Buj"

[programs.mainnet]
spin = "GSZNsGYUVXeisnKaKQ2mN6YQZScmWRG2wFnybX7F8Buj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
